# Site Settings 
remote_theme: just-the-docs/just-the-docs
title: Agastya Patri
description: labours of love
url: agastyapatri.github.io

twitter_username: papyruspatri
github_username:  agastyapatri


# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/agastyapatri/agastyapatri.github.io"
